name: Remove Expired Jobs

on:
  schedule:
    # Run nightly 1am
    - cron: 0 1 * * *

jobs:
  clean-jobs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install required packages
      run: |
        pip install requests pyaml urlchecker
    - name: Remove Expired Jobs
      run: |
        python scripts/clean_jobs.py
    - name: Run URLs-checker
      uses: urlstechie/urlchecker-action@0.0.34
      with:
        file_types: .md,.py,.yml
        print_all: false
        retry_count: 3
        timeout: 10
        exclude_patterns: supercomputing.org,https://pace.gatech.edu,https://www.linkedin.com,jobs.colorado.edu,zoom.us,danielskatz.org,usrse.github.io.wiki.git,ornl.gov
        exclude_files: README.md,SocialNetworks.yml,map.yml,_config.yml,tests/test_,.github/workflows,_posts/newsletters/

    # - name: Push Fixes
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     printf "GitHub Actor: ${GITHUB_ACTOR}\n"

    #     git config --global user.name "github-actions"
    #     git config --global user.email "github-actions@users.noreply.github.com"

    #     git add _data/jobs.yml _data/related-jobs.yml

    #     set +e
    #     git status | grep modified
    #     if [ $? -eq 0 ]; then
    #         set -e
    #         printf "Changes\n"
    #         git commit -m "Automated push to update jobs files $(date '+%Y-%m-%d')" || exit 0
    #         git push origin main
    #     else
    #         set -e
    #         printf "No changes\n"
    #     fi
