[files]
extend-exclude = [
    ".git/",
    ".github/workflows/typo_config.toml",
    "assets/js/*.min.*",
]
ignore-hidden = true
[default]
extend-ignore-re = [
    "Brain tailoRed stImulation protocoL",
    "Vas Vasiliadis",
]
